kind: Service
apiVersion: v1
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    service: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  loadBalancerIP: 35.224.21.104