version: '3'
services:
  mongo:
    image: mongo:3
  rabbitmq:
    image: rabbitmq:3-alpine
  sync:
    build: sync/
    image: registry.gitlab.com/cryptocurrencytracker/zeus/sync
    links:
      - rabbitmq
      - mongo
  aphrodite:
    build: aphrodite/
    image: registry.gitlab.com/cryptocurrencytracker/zeus/aphrodite
    links:
      - mongo
      - config-server
  config-server:
    build: config-server/
    image: registry.gitlab.com/cryptocurrencytracker/zeus/config-server  
  transaction-processor:
    build: transaction-processor/
    image: registry.gitlab.com/cryptocurrencytracker/zeus/transaction-processor
    links:
      - mongo
      - rabbitmq