apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: parity
  name: parity
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: parity
    spec:
      containers:
      - args:
        - --no-warp
        - --base-path=/var/lib/parity/data
        - --db-compaction=ssd
        - --mode=active
        - --cache-size=7168
        - --unsafe-expose
        image: parity/parity:stable
        name: parity
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/parity/data
          name: parity-data
        ports:
        - containerPort: 8545
        resources:
          requests:
            cpu: "1.2"
            memory: "9Gi"
      restartPolicy: Always
      volumes:
      - name: parity-data
        persistentVolumeClaim:
          claimName: parity-data
status: {}
