apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: sync
  name: sync
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        service: sync
    spec:
      containers:
      - image: registry.gitlab.com/cryptocurrencytracker/zeus/sync
        name: sync
        resources: {}
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
status: {}
