apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: transaction-processor
  name: transaction-processor
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: transaction-processor
    spec:
      containers:
      - image: registry.gitlab.com/cryptocurrencytracker/zeus/transaction-processor
        name: transaction-processor
        resources: {}
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
status: {}
