apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
  labels:
    service: mongodb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: mongodb
    spec:
      hostname: mongodb
      containers:
      - image: mongo:3
        name: mongodb
        resources: 
          requests:
            memory: "4G"
            cpu: 1
        volumeMounts:
        - mountPath: /data/db
          name: mongodb-data
        ports:
        - containerPort: 27017
      restartPolicy: Always
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-data
status: {}
