apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: aphrodite
  name: aphrodite
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: aphrodite
    spec:
      containers:
      - image: registry.gitlab.com/cryptocurrencytracker/zeus/aphrodite
        name: aphrodite
        resources: {}
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
status: {}
