apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
data:
  nginx.conf: |
    events {
      worker_connections  1024;  ## Default: 1024
    }
    http {
      server {
        listen 80;
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
            try_files $uri $uri/ /index.html =404;
        }
        location /api/ {
            proxy_pass http://aphrodite:8080/;
            limit_except GET {
                deny all;
            }
        }
        location /statsApi/ {
            proxy_pass http://messy-aphrodite:8080/;
        }
      }
    }

