apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
  labels:
    service: frontend
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: frontend
    spec:
      containers:
      - image: registry.gitlab.com/cryptocurrencytracker/zeus/aphrodite-frontend
        name: frontend
        resources: 
          requests:
            cpu: "200m"
        volumeMounts:
          - name: frontend-nginx-configmap
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      volumes:
        - name: frontend-nginx-configmap
          configMap:
            name: frontend-nginx-configmap
status: {}
