apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: config-server
  name: config-server
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        service: config-server
    spec:
      hostname: config-server
      containers:
      - image: registry.gitlab.com/cryptocurrencytracker/zeus/config-server
        name: config-server
        resources: {}
        ports:
        - containerPort: 8888
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
status: {}
