apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        service: rabbitmq
    spec:
      hostname: rabbitmq
      containers:
      - image: rabbitmq:3-alpine
        name: rabbitmq
        resources: {}
        ports:
        - containerPort: 5673
      restartPolicy: Always
status: {}
