apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\tools\kompose\kompose.exe convert -f .\docker-compose-kubernetes.yml
    kompose.version: 1.12.0 (0ab07be)
  creationTimestamp: null
  labels:
    io.kompose.service: transaction-processor
  name: transaction-processor
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: transaction-processor
    spec:
      containers:
      - image: registry.gitlab.com/cryptocurrencytracker/zeus/transaction-processor
        name: transaction-processor
        resources: {}
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
status: {}
