management:
   endpoint:
      health:
        show-details: "ALWAYS"

spring:
  rabbitmq:
    host: localhost
  data:
    mongodb:
      database: ethdb
      uri: mongodb://localhost:27017

      
web3j:
  client-address: http://localhost:8545
  httpTimeoutSeconds: 1
      