management:
   endpoint:
      health:
        show-details: "ALWAYS"

spring:
  rabbitmq:
    host: rabbitmq
  data:
    mongodb:
      database: ethdb
      uri: mongodb://mongodb:27017

web3j:
  client-address: http://parity:8545
  httpTimeoutSeconds: 0 